language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt

script:
  - ls
  - cd src
  - python -m matrix_semantic_map.test.TestMapBuilder
  - python -m matrix_semantic_map.test.test_OLSQueryWrapper
